# label_table_zz55ih.R
# 'label.table' attribute from it14ih sample dataset https://www.lisdatacenter.org/resources/self-teaching/

label_table_zz15ih <- list(
     hpartner = structure(0:1,
                          .Names = c("[0]head not living with partner",  "[1]head living with partner")),
     nhhmem13 = structure(0:5,
                          .Names = c("[0]no hh members 13 or younger",
                                     "[1]1 hh member 13 or younger", "[2]2 hh member 13 or younger",
                                     "[3]3 hh member 13 or younger", "[4]4 hh member 13 or younger",
                                     "[5]5 hh member 13 or younger")),
     nhhmem65 = structure(0:4,
                          .Names = c("[0]no hh members 65 or older",
                                     "[1]1 hh member 65 or older", "[2]2 hh members 65 or older",
                                     "[3]3 hh members 65 or older", "[4]4 hh members 65 or older")),
     grossnet = c(`[100]gross, taxes and contributions fully captured` = 100L,
                  `[110]gross, taxes and contributions collected` = 110L, `[120]gross, taxes and contributions imputed` = 120L,
                  `[200]net, taxes and contributions not captured` = 200L,
                  `[300]mixed, taxes and contributions insufficiently captured` = 300L,
                  `[310]mixed, total income account for full taxes and contributions, subcomponents do not` = 310L,
                  `[320]mixed, total income does not account for full taxes and contributions` = 320L),
     wave = structure(0:13,
                      .Names = c("[0]Historical Wave",
                                 "[1]Wave I", "[2]Wave II", "[3]Wave III", "[4]Wave IV", "[5]Wave V",
                                 "[6]Wave VI", "[7]Wave VII", "[8]Wave VIII", "[9]Wave IX",
                                 "[10]Wave X", "[11]Wave XI", "[12]Wave XII", "[13]Wave XIII")),
     dweltyp = c(`[100]house` = 100L, `[110]detached house` = 110L,
                 `[120]non-detached house` = 120L, `[200]multi-unit residential building` = 200L,
                 `[210]apartment/flat` = 210L, `[220]other multi-unit` = 220L,
                 `[300]other type of dwelling` = 300L, `[310]movable dwelling` = 310L,
                 `[320]informal dwelling` = 320L),
     rural = structure(0:1,
                       .Names = c("[0]not rural area", "[1]rural area")),
     region_it14 = structure(1:20,
                             .Names = c("[1]ITC1 - Piemonte",  "[2]ITC2 - Valle d'Aosta", "[3]ITC4 - Lombardia", "[4]ITH1 and ITH2 - Trentino",
                                        "[5]ITH3 - Veneto", "[6]ITH4 - Friuli", "[7]ITC3 - Liguria",
                                        "[8]ITH5 - Emilia Romagna", "[9]ITI1 - Toscana", "[10]ITI2 - Umbria",
                                        "[11]ITI3 - Marche", "[12]ITI4 - Lazio", "[13]ITF1 - Abruzzo",
                                        "[14]ITF2 - Molise", "[15]ITF3 - Campania", "[16]ITF4 - Puglia",
                                        "[17]ITF5 - Basilicata", "[18]ITF6 - Calabria", "[19]ITG1 - Sicilia",
                                        "[20]ITG2 - Sardegna")),
     locsz_it14 = structure(1:7,
                            .Names = c("[1]0-5.000 inhabitants",
                                       "[2]5.000-20.000 inhabitants", "[3]20.000-40.000 inhabitants",
                                       "[4]40.000-50.000 inhabitants", "[5]50.000-200.000 inhabitants",
                                       "[6]200.000-500.000 inhabitants", "[7]more than 500.000 inhabitants")),
     own = c(`[100]owned` = 100L, `[110]owned outright` = 110L,
             `[120]owned with mortgage` = 120L, `[200]not owned` = 200L,
             `[210]rented` = 210L, `[211]rented at market price` = 211L,
             `[212]subsidised rent` = 212L, `[220]free housing` = 220L,
             `[221]employer provided housing` = 221L, `[222]government/public provided housing` = 222L,
             `[223]provided by others` = 223L, `[224]illegal occupation` = 224L),
     farming = structure(0:1,
                         .Names = c("[0]no farming activity",
                                    "[1]farming activity")),
     nearn = structure(0:5,
                       .Names = c("[0]no hh member with labour income",
                                  "[1]1 hh member with labour income", "[2]2 hh members with labour income",
                                  "[3]3 hh members with labour income", "[4]4 hh members with labour income",
                                  "[5]5 hh members with labour income")),
     currency = c(`[36]AUD - Australian Dollar` = 36L,
                  `[40]ATS - Schilling (historic)` = 40L, `[56]BEF - Belgian franc (historic)` = 56L,
                  `[124]CAD - Canadian Dollar` = 124L, `[152]CLP - Chilean Peso` = 152L,
                  `[156]CNY - Yuan Renminbi` = 156L, `[170]COP - Colombian Peso` = 170L,
                  `[196]CYP - Cyprus Pound (historic)` = 196L, `[203]CZK - Czech Koruna` = 203L,
                  `[208]DKK - Danish Krone` = 208L, `[214]DOP - Dominican Peso` = 214L,
                  `[233]EEK - Estonian Kroon (historic)` = 233L, `[246]FIM - Markka (historic)` = 246L,
                  `[250]FRF - French Franc (historic)` = 250L, `[276]DEM - Deutsche Mark (historic)` = 276L,
                  `[300]GRD - Drachma (historic)` = 300L, `[320]GTQ - Quetzal` = 320L,
                  `[348]HUF - Forint` = 348L, `[352]ISK - Icelandic Krona` = 352L,
                  `[356]INR - Indian Rupee` = 356L, `[372]IEP - Irish Pound (historic)` = 372L,
                  `[376]ILS - New Israeli Sheqel` = 376L, `[380]ITL - Italian Lira (historic)` = 380L,
                  `[392]JPY - Yen` = 392L, `[410]KRW - Won` = 410L, `[440]LTL - Lithuanian Litas (historic)` = 440L,
                  `[442]LUF - Luxembourg Franc (historic)` = 442L, `[484]MXN - Mexican Peso` = 484L,
                  `[528]NLG - Netherlands Guilder (historic)` = 528L, `[578]NOK - Norwegian Krone` = 578L,
                  `[590]PAB - Balboa` = 590L, `[600]PYG - Guarani` = 600L,
                  `[604]PEN - Nuevo Sol` = 604L, `[616]PLZ - old Zloty (historic)` = 616L,
                  `[642]ROL - old Leu (historic)` = 642L, `[643]RUB - Russian Ruble` = 643L,
                  `[703]SKK - Slovak Koruna (historic)` = 703L, `[704]VND - Vietnamese Dong` = 704L,
                  `[705]SIT - Tolar (historic)` = 705L, `[710]ZAR - Rand` = 710L,
                  `[724]ESP - Spanish Peseta (historic)` = 724L, `[752]SEK - Swedish Krona` = 752L,
                  `[756]CHF - Swiss Franc` = 756L, `[788]TND - Tunisian Dinar` = 788L,
                  `[810]RUR - Russian Ruble (historic)` = 810L, `[818]EGP - Egyptian Pound` = 818L,
                  `[826]GBP - Pound Sterling` = 826L, `[840]USD - US Dollar` = 840L,
                  `[858]UYU - Peso Uruguayo` = 858L, `[901]TWD - New Taiwan Dollar` = 901L,
                  `[902]ILP - Israeli Pound (historic)` = 902L, `[903]MXP - old Mexican Peso (historic)` = 903L,
                  `[941]RSD - Serbian Dinar` = 941L, `[952]XOF - Franc CFA BCEAO` = 952L,
                  `[978]EUR - Euro` = 978L, `[981]GEL - Georgian Lari` = 981L,
                  `[985]PLN - Zloty` = 985L, `[986]BRL - Brazilian Real` = 986L),
     nhhmem = structure(1:10,
                        .Names = c("[1]1 hh member",
                                   "[2]2 hh members", "[3]3 hh members", "[4]4 hh members",
                                   "[5]5 hh members", "[6]6 hh members", "[7]7 hh members",
                                   "[8]8 hh members", "[9]9 hh members", "[10]10 hh members")),
     nhhmem17 = structure(0:5,
                          .Names = c("[0]no hh members 17 or younger",
                                     "[1]1 hh member 17 or younger", "[2]2 hh member 17 or younger",
                                     "[3]3 hh member 17 or younger", "[4]4 hh member 17 or younger",
                                     "[5]5 hh member 17 or younger")),
     hhtype = c(`[100]one person household` = 100L,
                `[210]couple without children` = 210L, `[220]couple with children` = 220L,
                `[230]one parent with children` = 230L, `[310]couple without children and relatives` = 310L,
                `[320]couple with children and relatives` = 320L, `[330]one parent with children and relatives` = 330L,
                `[400]relatives living together (no family nucleus)` = 400L,
                `[510]couple without children and nonrelatives` = 510L, `[520]couple with children and nonrelatives` = 520L,
                `[530]one parent with children and nonrelatives` = 530L,
                `[610]couple without children and relatives and nonrelatives` = 610L,
                `[620]couple with children and relatives and nonrelatives` = 620L,
                `[630]one parent with children and relatives and nonrelatives` = 630L,
                `[700]relatives and nonrelatives living together (no family nucleus)` = 700L,
                `[800]nonrelatives living together` = 800L, `[900]head and other` = 900L,
                `[910]couple without children and other` = 910L, `[920]couple with children and other` = 920L,
                `[930]one parent with children and other` = 930L))
