
# lws_income_variables ----------------------------------------------------

lws_income_variables <- c(
  "hitotal", "pitotal", "hifactor", "hitransfer",
  "dhi", "hitotal", "hxitsc",
  "hvalgs", "hi13" ,"hi14", "hi47", "hi53",
  "dhci", "hvalgs", "hxitsc",
  "hifactor", "hilabour", "hicapital",
  "hitransfer", "hipension", "hipubsoc", "hiprivate",
  "hpublic", "hpub_i", "ppub_i", "hpub_u", "hpub_a",
  "hid", "hi11", "hi12", "hi121", "hi21", "hi22", "hi31", "hi311",
  "hi312", "hi32", "hi33", "hi331", "hi332", "hi41", "hi411", "hi412",
  "hi42", "hi421", "hi422", "hi43", "hi44", "hi45", "hi46", "hi471",
  "hi51", "hi511", "hi52", "hi521", "hi522", "hi531", "hi532",
  "pilabour", "pi11", "pi12", "pi13", "pipension",
  "pi31", "pi311", "pi312", "pi32", "pi331", "pi332", "pi33", "pi411",
  "pi42", "pi421", "pi422", "pi43", "pi44", "pi511"
)


lws_non_income_variables <- c("hid", "inum", "cir", "cig", "chc", "cha", "cnc", "cna", "ppr",
                              "ppy", "pir", "pia1", "pia2", "pia3", "pia4", "piy1", "piy2",
                              "piy3", "piy4", "pit1", "pit2", "pit3", "pit4", "piw1", "piw2",
                              "piw3", "piw4", "pim1", "pim2", "pim3", "pim4", "bopc", "bonc_c",
                              "boue", "boea", "bolc", "bocc1_c", "bocc2_c", "bocs_c", "bocd1_c",
                              "bocd2_c", "boef_c", "boee1_c", "boee2_c", "bus1_c", "bus2_c",
                              "bus3_c", "cia", "dnw", "anw", "inw", "tnw", "hanrp", "hanro",
                              "hanr", "hannb", "hanncv", "hanncd", "hafc", "hafib", "hafis",
                              "hafii", "hafo", "han", "hann", "hannc", "hanno", "haf", "hafi",
                              "has", "hasi", "hasil", "hasip", "haso", "hasodb", "hasodc",
                              "hass", "hassdb", "hassdc", "ha", "hlrp", "hlro", "hlncv", "hlncd",
                              "hlno", "hlr", "hln", "hlni", "hlnc", "hlne", "hl", "hlsr", "hlsni",
                              "hlsn", "hlsrp", "hlsro", "hlsng", "hlsnn", "nearn", "region_c",
                              "locsz_c", "area_c", "rural", "own", "dweltyp", "farming", "did",
                              "dname", "cname", "iso2", "iso3", "year", "wave", "currency",
                              "grossnet", "nhhmem", "nhhmem65", "nhhmem17", "nhhmem13", "hhtype",
                              "hpartner", "hwgt", "hpopwgt", "hwgta", "fhimpu", "pid", "basb",
                              "basp1", "basp2", "basp3", "basp4", "basp5", "basp6", "basp7",
                              "basp8", "basp9", "bafr1_c", "bafr2_c", "bafr3_c", "bafp1_c",
                              "bafp2_c", "bafl1_c", "bafl2_c", "bafl3_c", "bafl4_c", "bafi1_c",
                              "bafi2_c", "bafi3_c", "bafi4_c", "bafi5_c", "ssyc", "pasil",
                              "pasip", "pasodc", "pass", "pas", "pasi", "paso", "pasodb", "passdb",
                              "passdc", "lfs", "emp", "emp_ilo", "informal", "parleave", "secjob",
                              "weeks", "hours1", "hourstot", "ptime1", "status1", "temp1",
                              "public1", "ind1_c", "indd1", "indc1", "indb1", "inda1", "occ1_c",
                              "occb1", "occa1", "fyft", "wexptl", "enroll", "educ_c", "educlev",
                              "educ", "illiterate", "edyrs", "edmom_c", "eddad_c", "ctrybrth",
                              "citizen", "yrsresid", "ethnic_c", "migrat_c", "immigr_c", "immigr",
                              "disabled", "health_c", "fpimpu", "age", "sex", "marital", "relation",
                              "partner", "parents", "nchildren", "ageyoch", "pwgt", "ppopwgt",
                              "pwgta")


# lws_reference_year ------------------------------------------------------

data_inc_ref_year <- tibble::tribble(
  ~dname, ~income_reference_year,
  "au04",                  2004L,
  "au10",                  2010L,
  "au14",                  2014L,
  "au16",                  2016L,
  "au18",                  2018L,
  "at11",                  2009L,
  "at14",                  2013L,
  "at17",                  2016L,
  "ca99",                  1998L,
  "ca05",                  2004L,
  "ca12",                  2011L,
  "ca16",                  2015L,
  "ca19",                  2018L,
  "cl07",                  2007L,
  "cl14",                  2014L,
  "cl17",                  2017L,
  "fi09",                  2009L,
  "fi13",                  2013L,
  "fi16",                  2016L,
  "de02",                  2001L,
  "de07",                  2006L,
  "de12",                  2011L,
  "de17",                  2016L,
  "gr09",                  2009L,
  "gr14",                  2014L,
  "gr18",                  2017L,
  "it95",                  1995L,
  "it00",                  2000L,
  "it04",                  2004L,
  "it08",                  2008L,
  "it10",                  2010L,
  "it14",                  2014L,
  "it16",                  2016L,
  "jp04",                  2003L,
  "jp09",                  2008L,
  "jp11",                  2010L,
  "jp14",                  2013L,
  "lu10",                  2009L,
  "lu14",                  2013L,
  "lu18",                  2017L,
  "no10",                  2010L,
  "no13",                  2013L,
  "no16",                  2016L,
  "no19",                  2019L,
  "no20",                  2020L,
  "no21",                  2021L,
  "sk10",                  2010L,
  "sk14",                  2013L,
  "sk17",                  2016L,
  "si14",                  2013L,
  "si17",                  2016L,
  "za15",                  2015L,
  "za17",                  2017L,
  "es02",                  2001L,
  "es05",                  2004L,
  "es08",                  2007L,
  "es11",                  2011L,
  "es14",                  2013L,
  "es17",                  2016L,
  "se02",                  2002L,
  "se05",                  2005L,
  "uk07",                  2007L,
  "uk09",                  2009L,
  "uk11",                  2011L,
  "uk13",                  2013L,
  "uk15",                  2015L,
  "uk17",                  2017L,
  "uk19",                  2019L,
  "us95",                  1994L,
  "us98",                  1997L,
  "us01",                  2000L,
  "us04",                  2003L,
  "us07",                  2006L,
  "us10",                  2009L,
  "us13",                  2012L,
  "us16",                  2015L,
  "us19",                  2018L,
  "ee13",                  2012L,
  "ee17",                  2016L
)

#
# usethis::use_data(lws_income_variables,
#                   lws_non_income_variables,
#                   internal = TRUE, overwrite = TRUE)

usethis::use_data(data_inc_ref_year, internal = FALSE, overwrite = TRUE)

sysdata_filenames <- load("R/sysdata.rda")
save(list = c(sysdata_filenames, "lws_income_variables", "lws_non_income_variables"),
     file = "R/sysdata.rda")




#ghhhasdjajd
