# helper-read_lissy_files.R

names_ih_file <- c("hid", "dhi", "hitotal", "hifactor", "hitransfer", "hilabour",
                   "hi11", "hi12", "hi121", "hi13", "hi14", "hicapital", "hi21",
                   "hi22", "hipension", "hi31", "hi311", "hi312", "hi32", "hi33",
                   "hi331", "hi332", "hpublic", "hpub_i", "hpub_u", "hpub_a", "hipubsoc",
                   "hi41", "hi411", "hi412", "hi42", "hi421", "hi422", "hi43", "hi44",
                   "hi45", "hi46", "hi47", "hi471", "hiprivate", "hi51", "hi511",
                   "hi52", "hi521", "hi522", "hi53", "hi531", "hi532", "dhci", "hvalgs",
                   "hxitsc", "hxitax", "hxscont", "hxotax", "hxptax", "hxvcont",
                   "hxiht", "hxalim", "hxremit", "hxmort", "hxintm", "hxloan", "hxintl",
                   "hhouscost", "hrenti", "hcexp", "hc1", "hc2", "hc3", "hc4", "hc41",
                   "hc5", "hc6", "hc7", "hc8", "hc9", "hc10", "hc11", "hc12", "helabour",
                   "hecgain", "heinherit", "heoth", "nearn", "region_c", "locsz_c",
                   "area_c", "rural", "own", "dweltyp", "farming", "did", "dname",
                   "cname", "iso2", "iso3", "year", "wave", "currency", "grossnet",
                   "nhhmem", "nhhmem65", "nhhmem17", "nhhmem13", "hhtype", "hpartner",
                   "hwgt", "hpopwgt", "hwgta", "nrooms", "housing_c", "ore_c", "typehh", 
                   "nhhmem6", "tchild", "hi321", "hi322", "hi323", "hi48", "hi4111", "hi4112", 
                   "hi451", "hi452", "hi54", "hi541", "hi542", "hi512", "hxitadj", "hxitcred", "hepension")


names_ip_file <- c("hid", "pitotal", "pilabour", "pi11", "pi12", "pi13", "pipension",
                   "pi31", "pi311", "pi312", "pi32", "pi331", "pi332", "pi33", "ppub_i",
                   "pi411", "pi42", "pi421", "pi422", "pi43", "pi44", "pi511", "pelabour",
                   "pxitax", "pxscont", "pxitsc", "pxvcont", "lfs", "emp", "emp_ilo",
                   "informal", "parleave", "secjob", "weeks", "hours1", "hourstot",
                   "ptime1", "status1", "temp1", "public1", "ind1_c", "indd1", "indc1",
                   "indb1", "inda1", "occ1_c", "occb1", "occa1",
                   "fyft", "wexptl", "enroll", "educ_c", "educlev", "educ", "illiterate",
                   "edyrs", "edmom_c", "eddad_c", "ctrybrth", "citizen", "yrsresid",
                   "ethnic_c", "migrat_c", "immigr_c", "immigr", "disabled", "health_c",
                   "did", "dname", "cname", "iso2", "iso3", "year", "wave", "currency",
                   "grossnet", "age", "sex", "marital", "relation", "partner",
                   "parents", "nchildren", "ageyoch", "pwgt", "ppopwgt", "pwgta",
                   "pid", "depchild", "oneparent", "momnum", "dadnum", "partnum", "oneparent_c", 
                   "illness_c", "health2_c", "parleave_c", "occdad_c", "occmom_c", "wage1", 
                   "hwage1", "occc1", "weeksft", "pi321", "pi322", "pi323", "pi48", "pi4111", 
                   "pi4112", "pi54", "pi541", "pi542", "pxitadj", "pxitcred", "pepension")


names_wh_file <- c("hid", "inum", "cir", "cig", "chc", "cha", "cnc", "cna", "ppr",
                  "ppy", "pir", "pia1", "pia2", "pia3", "pia4", "piy1", "piy2",
                  "piy3", "piy4", "pit1", "pit2", "pit3", "pit4", "piw1", "piw2",
                  "piw3", "piw4", "pim1", "pim2", "pim3", "pim4", "bopc", "bonc_c",
                  "boue", "boea", "bolc", "bocc1_c", "bocc2_c", "bocs_c", "bocd1_c",
                  "bocd2_c", "boef_c", "boee1_c", "boee2_c", "bus1_c", "bus2_c",
                  "bus3_c", "cia", "dnw", "anw", "inw", "tnw", "hanrp", "hanro",
                  "hanr", "hannb", "hanncv", "hanncd", "hafc", "hafib", "hafis",
                  "hafii", "hafo", "han", "hann", "hannc", "hanno", "haf", "hafi",
                  "has", "hasi", "hasil", "hasip", "haso", "hasodb", "hasodc",
                  "hass", "hassdb", "hassdc", "ha", "hlrp", "hlro", "hlncv", "hlncd",
                  "hlne", "hlno", "hlr", "hln", "hlni", "hlnc", "hl", "hlsr", "hlsni",
                  "hlsn", "hlsrp", "hlsro", "hlsng", "hlsnn", "dhi", "hitotal",
                  "hifactor", "hitransfer", "hilabour", "hi11", "hi12", "hi121",
                  "hi13", "hi14", "hicapital", "hi21", "hi22", "hipension", "hi31",
                  "hi311", "hi312", "hi32", "hi33", "hi331", "hi332", "hpublic",
                  "hpub_i", "hpub_u", "hpub_a", "hipubsoc", "hi41", "hi411", "hi412",
                  "hi42", "hi421", "hi422", "hi43", "hi44", "hi45", "hi46", "hi47",
                  "hi471", "hiprivate", "hi51", "hi511", "hi52", "hi521", "hi522",
                  "hi53", "hi531", "hi532", "dhci", "hvalgs", "hxitsc", "hxitax",
                  "hxscont", "hxotax", "hxptax", "hxvcont", "hxiht", "hxalim",
                  "hxremit", "hxmort", "hxintm", "hxloan", "hxintl", "hhouscost",
                  "hrenti", "hcexp", "hc1", "hc2", "hc3", "hc4", "hc41", "hc5",
                  "hc6", "hc7", "hc8", "hc9", "hc10", "hc11", "hc12", "helabour",
                  "hecgain", "heinherit", "heoth", "nearn", "region_c", "locsz_c",
                  "area_c", "rural", "own", "dweltyp", "farming", "did", "dname",
                  "cname", "iso2", "iso3", "year", "wave", "currency", "grossnet",
                  "nhhmem", "nhhmem65", "nhhmem17", "nhhmem13", "hhtype", "hpartner",
                  "hwgt", "hpopwgt", "hwgta", "nrooms", "housing_c", "ore_c", "typehh", 
                  "nhhmem6", "tchild", "hi321", "hi322", "hi323", "hi48", "hi4111", 
                  "hi4112", "hi451", "hi452", "hi54", "hi541", "hi542", "hi512", "hxitadj", 
                  "hxitcred", "hepension", "hafct", "hafcs", "hafiss", "hafiso", "hafom")


names_wp_file <- c("hid", "inum", "pid", "basb", "basp1", "basp2", "basp3", "basp4",
                   "basp5", "basp6", "basp7", "basp8", "basp9", "bafr1_c", "bafr2_c",
                   "bafr3_c", "bafp1_c", "bafp2_c", "bafl1_c", "bafl2_c", "bafl3_c",
                   "bafl4_c", "bafi1_c", "bafi2_c", "bafi3_c", "bafi4_c", "bafi5_c",
                   "ssyc", "pasil", "pasip", "pasodc", "pass", "pas", "pasi", "paso",
                   "pasodb", "passdb", "passdc", "pitotal", "pilabour", "pi11",
                   "pi12", "pi13", "pipension", "pi31", "pi311", "pi312", "pi32",
                   "pi331", "pi332", "pi33", "ppub_i", "pi411", "pi42", "pi421",
                   "pi422", "pi43", "pi44", "pi511", "pelabour", "pxitax", "pxscont",
                   "pxitsc", "pxvcont", "lfs", "emp", "emp_ilo", "informal", "parleave",
                   "secjob", "weeks", "hours1", "hourstot", "ptime1", "status1",
                   "temp1", "public1", "ind1_c", "indd1", "indc1", "indb1", "inda1",
                   "occ1_c", "occb1", "occa1", "fyft", "wexptl",
                   "enroll", "educ_c", "educlev", "educ", "illiterate", "edyrs",
                   "edmom_c", "eddad_c", "ctrybrth", "citizen", "yrsresid", "ethnic_c",
                   "migrat_c", "immigr_c", "immigr", "disabled", "health_c", "did",
                   "dname", "cname", "iso2", "iso3", "year", "wave", "currency",
                   "grossnet", "age", "sex", "marital", "relation", "partner",
                   "parents", "nchildren", "ageyoch", "pwgt", "ppopwgt", "pwgta", "depchild", 
                   "oneparent", "momnum", "dadnum", "partnum", "oneparent_c", "illness_c", 
                   "health2_c", "parleave_c", "occdad_c", "occmom_c", "wage1", "hwage1", 
                   "occc1", "weeksft", "pi321", "pi322", "pi323", "pi48", "pi4111", "pi4112", 
                   "pi54", "pi541", "pi542", "pxitadj", "pxitcred", "pepension")


names_eh_file <- c("hid", "dhi", "hitotal", "hifactor", "hitransfer", "hilabour",
                   "hi11", "hi12", "hi121", "hi13", "hi14", "hicapital", "hi21",
                   "hi22", "hipension", "hi31", "hi311", "hi312", "hi32", "hi33",
                   "hi331", "hi332", "hpublic", "hpub_i", "hpub_u", "hpub_a", "hipubsoc",
                   "hi41", "hi411", "hi412", "hi42", "hi421", "hi422", "hi43", "hi44",
                   "hi45", "hi46", "hi47", "hi471", "hiprivate", "hi51", "hi511",
                   "hi52", "hi521", "hi522", "hi53", "hi531", "hi532", "dhci", "hvalgs",
                   "hxitsc", "hxitax", "hxscont", "hxotax", "hxptax", "hxvcont",
                   "hxiht", "hxalim", "hxremit", "hxmort", "hxintm", "hxloan", "hxintl",
                   "hhouscost", "hrenti", "hcexp", "hc1", "hc2", "hc3", "hc4", "hc41",
                   "hc5", "hc6", "hc7", "hc8", "hc9", "hc10", "hc11", "hc12", "helabour",
                   "hecgain", "heinherit", "heoth", "nearn", "region_c", "locsz_c",
                   "area_c", "rural", "own", "dweltyp", "farming", "did", "dname",
                   "cname", "iso2", "iso3", "year", "wave", "currency", "grossnet",
                   "nhhmem", "nhhmem65", "nhhmem17", "nhhmem13", "hhtype", "hpartner",
                   "hwgt", "hpopwgt", "hwgta", "elect", "slight",
                   "scook", "wat", "tfacil", "sfacil", "hfacil", "toif", "toif_sh",
                   "grbg_dsp", "car", "car_n", "truck", "truck_n", "mbcycle", "mbcycle_n",
                   "telv", "telv_n", "radio", "radio_n", "satd_rec", "satd_rec_n",
                   "player", "player_n", "camera", "camera_n", "game", "game_n",
                   "telph", "telph_n", "fax", "fax_n", "computer", "computer_n",
                   "internet", "internet_n", "refrg", "refrg_n", "cooker", "cooker_n",
                   "microwave", "microwave_n", "skitapp", "skitapp_n", "wash", "wash_n",
                   "dryer", "dryer_n", "dshwsh", "dshwsh_n", "cond", "cond_n", "fan",
                   "fan_n", "heater", "heater_n", "waheat", "waheat_n", "sewing",
                   "sewing_n", "vacuum", "vacuum_n", "iron", "iron_n", "odur", "odur_n",
                   "livestok", "livestok_n", "rice", "grain", "bread", "past", "cerpre",
                   "cerown", "smeat", "cmeat", "omeat", "chmeat", "lmeat", "meatown",
                   "fish", "seaf", "fshseaown", "milk", "yogh", "ches", "egg", "dairyown",
                   "ooil", "oil", "but", "fat", "oilfatown", "fruitexp", "fruitown",
                   "vegexp", "vegown", "sugarexp", "sugarown", "spicexp", "spicown",
                   "bevexp", "bevown", "othfexp", "othfown", "totgikd", "alc", "tob",
                   "cloth", "mclo", "char", "footw", "schclth", "repdw", "wdwe",
                   "edwe", "hsfur", "furrep", "hstex", "mhapl", "shapl", "rappl",
                   "hust", "mhope", "shope", "hsgs", "pmedp", "taeq", "medserv",
                   "medabr", "trveh", "oteq", "trserv", "schserv", "pttserv", "tteqp",
                   "culdur", "culeqp", "culser", "schcul", "preduc", "seduc", "teduc",
                   "oeduc", "educabr", "catser", "schrst", "accom", "pcexp", "spexp",
                   "fexp", "fees", "ptransf", "nrooms", "housing_c", "ore_c", "typehh", 
                   "nhhmem6", "tchild", "hi321", "hi322", "hi323", "hi48", "hi4111", "hi4112", "hi451", 
                   "hi452", "hi54", "hi541", "hi542", "hi512", "hxitadj", "hxitcred", "hepension")


names_ep_file <- c("hid", "pid", "pitotal", "pilabour", "pi11", "pi12", "pi13",
                   "pipension", "pi31", "pi311", "pi312", "pi32", "pi33", "pi331",
                   "pi332", "ppub_i", "pi411", "pi42", "pi421", "pi422", "pi43",
                   "pi44", "pi511", "pelabour", "pxitax", "pxscont", "pxitsc", "pxvcont",
                   "lfs", "emp", "emp_ilo", "informal", "parleave", "secjob", "weeks",
                   "hours1", "hourstot", "ptime1", "status1", "temp1", "public1",
                   "ind1_c", "indd1", "indc1", "indb1", "inda1", "occ1_c", "occb1",
                   "occa1", "fyft", "wexptl", "enroll", "educ_c",
                   "educlev", "educ", "illiterate", "edyrs", "edmom_c", "eddad_c",
                   "ctrybrth", "citizen", "yrsresid", "ethnic_c", "migrat_c", "immigr_c",
                   "immigr", "disabled", "health_c", "did", "dname", "cname", "iso2",
                   "iso3", "year", "wave", "currency", "grossnet", "age",
                   "sex", "marital", "relation", "partner", "parents", "nchildren",
                   "ageyoch", "pwgt", "ppopwgt", "pwgta", "depchild", 
                   "oneparent", "momnum", "dadnum", "partnum", "oneparent_c", "illness_c", 
                   "health2_c", "parleave_c", "occdad_c", "occmom_c", "wage1", "hwage1", 
                   "occc1", "weeksft", "pi321", "pi322", "pi323", "pi48", "pi4111", "pi4112", 
                   "pi54", "pi541", "pi542", "pxitadj", "pxitcred", "pepension")
